# Generated by Django 2.2.3 on 2019-08-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190730_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_comments',
        ),
    ]
